### ISSUE TITLE
Live stream ?

### ISSUE THREAD

**Issue by SimonMellerin** [mrpjevans/3dcamera#1]
Hi,

I was wondering if your project can be use to make a live stream ?

My idea is to try to build a real-life 3rd person view, but I don't know if it could be doable with your setup. Does it lag ?

Thanks,
Simon

**Comment by mrpjevans** [comment]
Sadly the lag is too great for this to work (although you could record two separate streams and sync them later - but that's a lot of work!). Maybe a better approach would be StereoPi: https://stereopi.com/

**Comment by SimonMellerin** [comment]
Thanks for your answer, I will check that !

**Comment by SimonMellerin** [comment]
seems to be exactly what i want to do : https://stereopi.com/blog/you-3rd-person-view-stereopi-oculus-go
